### ISSUE TITLE
Add variables in README

### ISSUE THREAD

**Issue by akwiatkowski** [philnash/crotp#1]
```
# Generate a code
hotp.generate(counter)
# => "423748"
```

`counter` is not defined and I'm no sure what return `generate` method. Would be better to add variable names like `token = hotp.generate(counter)` if `generate` return `token` :)

**Comment by philnash** [comment]
Thanks for the feedback @akwiatkowski. I've updated the README and included a file in `examples/` that you might find useful. Does this improve the, admittedly minimal, documentation for now?

**Comment by akwiatkowski** [comment]
@philnash It's that I wanted. Thanks. I prefer the most basic stuff in `README` and read spec if not example is available.

**Comment by philnash** [comment]
Cool. I need to document the whole thing better anyway, but pushing it to GitHub is intended to encourage me to finish it off properly. Thanks for your feedback though, I'll work to make this as clear as I can.
