### ISSUE TITLE
Won't build on Crystal >= 0.31.0

### ISSUE THREAD

**Issue by repomaa** [philnash/crotp#11]
The dependency base32 is broken since crystal 0.31.0 floor division changes. I forked the project and made a [PR](https://github.com/noumar/base32/pull/7) but don't see it being merged in the near future. A temporary workaround would be for you to use [my fork](https://github.com/repomaa/base32/tree/topic/crystal-0-31-0) instead.

**Comment by philnash** [comment]
Used your fork and released v0.5.0 which now builds on 0.31.0.
