### ISSUE TITLE
Error evaluating epoch method

### ISSUE THREAD

**Issue by Xosmond** [philnash/crotp#6]
Hello, first of all, I want to thank you, I was going to build this from scratch and it would take many hours so thank you. Second im getting `undefined method epoch` when using the lib, I had to change `.epoch` to `.to_unix`. I made a PR if you are interested

**Comment by philnash** [comment]
Hey, thanks for fixing this. I guess it's something that changed in a recent version of Crystal.

**Comment by philnash** [comment]
Pushed and available as version 0.2.0.

Thanks again!
